stages:                          
 - build                         
 - deploy                        
    
maven-build:                     
    image: maven:3-jdk-17          
    stage: build                   
    script: "mvnw package -B"
    artifacts:              
        paths:
            - target/gitlab-ci-demo.jar
    tags:
        - localhost