stages:                          
    - build                         
    - deploy                        

before_script:
  - source /etc/profile

compile:                     
    image: maven:3-sapmachine-17          
    stage: build                   
    script: "mvn clean compile -B"
    artifacts:              
        paths:
            - target/eTWIG.jar
    tags:
        - localhost

test:                     
    image: maven:3-sapmachine-17          
    stage: build                   
    script: "mvn clean test -B"
    allow_failure: true
    artifacts:              
        paths:
            - target/eTWIG.jar
    tags:
        - localhost