stages:                          
    - build                         
    - tests
    - deploy                        

before_script:
  - source /etc/profile

compile:                     
    image: maven:3-sapmachine-17          
    stage: build                   
    script: "mvn compile -B"
    tags:
        - localhost

test:     
    image: maven:3-sapmachine-17                          
    stage: tests                   
    script: "mvn test -B"
    allow_failure: true
    tags:
        - localhost